### PR TITLE
Feature/swift5

### PR DESCRIPTION
**Pull request by andy380743909**
update project to Swift 5, and resolve some issues

### CODE REVIEW

**Comment by profburke** [comment]
@andy380743909 thanks for the PR. It just so happens that I've been planning on working on this project and some other Lua-iOS efforts (such as updating a SPM that provides a Lua interpreter). So the timing is great!

I have only spent a little time so far looking at your PR and the existing master branch and one issue I need to figure out is that when I try running (either branch) I'm not getting any keyboard input.

I just wanted to check with you to see if you had any issues along those lines and if so, did you have to do anything in particular to resolve it. Hopefully later today I'll have more time to look this over and figure out what's going wrong--possibly I'm overlooking something simple.

Also, should mention I'm using Xcode Version 11.5 (11E608c) -- which version of Xcode are you using?

**Comment by andy380743909** [comment]
Hi @profburke，the code works fine on my mac，my Xcode Version 11.5 (11E608c).

I didn't do anything with the UI, I just fixed the Swift syntax errors, so I don't know what happened with the input.
You can check whether the app is freezed, deadlocked?

**Comment by profburke** [comment]
@andy380743909 -- so I'm not sure what the problem was -- other than probably me just doing something dumb. Works fine now.

Thanks again for the PR.

I have one question about the last commit. So since `system` was remove, I agree with the need to do something to `os_execute`, but I'm not seeing something about what the proposed code does. It looks to me like it just forces calls to `os_execute` to remove subdirectories assuming that that `cmd` happens to be a path.

I think what I may do instead is just change `os_execute` to return nil and an error message. Maybe later on I might try and make use of https://github.com/holzschu/ios_system or similar.

What do you think?

**Comment by andy380743909** [comment]
@profburke I think you are right. The. solution in my PR is not good. I misunderstood the os_execute function, and just took someone's solution.
 
I will revert the wrong code.

The ios_system is a nice library.

**Pull request merged**
